# Generated by Django 2.2 on 2022-11-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221128_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prod',
            new_name='prodt',
        ),
    ]
